/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zaren_DiscoverTask */

#ifndef _Included_com_zaren_HdhomerunSignalMeterLib_data_DiscoverTask
#define _Included_com_zaren_HdhomerunSignalMeterLib_data_DiscoverTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_DiscoverTask
 * Method:    discover
 * Signature: ()Lcom/zaren/data/HdhomerunDiscoverDeviceArray;
 */
JNIEXPORT jobject JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_DiscoverTask_discover
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
