/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice */

#ifndef _Included_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
#define _Included_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_serialVersionUID
#define com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_serialVersionUID 1942906208628106963i64
/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetTunerChannel
 * Signature: (ILcom/zaren/HdhomerunSignalMeterLib/data/JniString;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetTunerChannel
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIcreateNewDevice
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIcreateNewDevice
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIsetChannelMap
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIsetChannelMap
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIsetTunerChannel
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIsetTunerChannel
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIsetTunerVChannel
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIsetTunerVChannel
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIwaitForLock
 * Signature: (ILcom/zaren/HdhomerunSignalMeterLib/data/TunerStatus;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIwaitForLock
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetTunerStreamInfo
 * Signature: (ILcom/zaren/HdhomerunSignalMeterLib/data/JniString;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetTunerStreamInfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetTunerStatus
 * Signature: (I)Lcom/zaren/HdhomerunSignalMeterLib/data/TunerStatus;
 */
JNIEXPORT jobject JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetTunerStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetSupported
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetSupported
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIdestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIdestroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetChannelMap
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetChannelMap
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIupdateTunerStatus
 * Signature: (ILcom/zaren/HdhomerunSignalMeterLib/data/TunerStatus;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIupdateTunerStatus
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIupdateTunerVStatus
 * Signature: (ILcom/zaren/HdhomerunSignalMeterLib/data/TunerVStatus;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIupdateTunerVStatus
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetTunerVStatus
 * Signature: (I)Lcom/zaren/HdhomerunSignalMeterLib/data/TunerVStatus;
 */
JNIEXPORT jobject JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetTunerVStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetModel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIcreateChannelList
 * Signature: (Ljava/lang/String;Lcom/zaren/HdhomerunSignalMeterLib/data/ChannelList;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIcreateChannelList
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetTunerVChannel
 * Signature: (ILcom/zaren/HdhomerunSignalMeterLib/data/JniString;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetTunerVChannel
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetFirmwareVersion
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetFirmwareVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetLockkeyOwner
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetLockkeyOwner
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetTunerTarget
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetTunerTarget
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIsetVar
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIsetVar
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetVar
 * Signature: (ILjava/lang/String;Lcom/zaren/HdhomerunSignalMeterLib/data/JniString;Lcom/zaren/HdhomerunSignalMeterLib/data/JniString;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetVar
  (JNIEnv *, jobject, jint, jstring, jobject, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNItunerLockeyRequest
 * Signature: (ILcom/zaren/HdhomerunSignalMeterLib/data/JniString;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNItunerLockeyRequest
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNItunerLockeyRelease
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNItunerLockeyRelease
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNItunerLockeyForce
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNItunerLockeyForce
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIgetTunerProgram
 * Signature: (ILcom/zaren/HdhomerunSignalMeterLib/data/JniString;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIgetTunerProgram
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIsetTunerProgram
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIsetTunerProgram
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIsetTunerTarget
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIsetTunerTarget
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice
 * Method:    JNIstreamStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zaren_HdhomerunSignalMeterLib_data_HdhomerunDevice_JNIstreamStop
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
